### PR TITLE
Rename "data management" tool in Data Exploration to Cell sets and Metadata and remove tabs

### PR DESCRIPTION
**Pull request by ivababukova**
# Description
I was looking at Data Exploration and trying to talk to someone about this "data management" tool. Because it has the same name as the data management module, it is ambiguous to talk about it. I talked to Vicky and she suggested to change it to "Cell sets and Metadata" instead.

# Details
#### URL to issue
N/A

#### Link to staging deployment URL (or set N/A)
N/A

#### Links to any PRs or resources related to this PR
N/A

#### Integration test branch
master

# Merge checklist
Your changes will be ready for merging after all of the steps below have been completed.

### Code updates
Have best practices and ongoing refactors being observed in this PR
- [ ] Migrated any selector / reducer used to the new format.

### Manual/unit testing
- [ ] Tested changes using InfraMock locally **or** no tests required for change, e.g. Kubernetes chart updates.
- [ ] Validated that current unit tests for code work as expected and are sufficient for code coverage **or** no unit tests required for change, e.g. documentation update.
- [ ] Unit tests written **or** no unit tests required for change, e.g. documentation update.

### Integration testing
**You must check the box below** to run integration tests on the latest commit on your PR branch.
Integration tests have to pass before the PR can be merged. Without checking the box, your PR
**will not pass** the required status checks for merging.

- [ ] Started end-to-end tests on the latest commit.

### Documentation updates
- [ ] Relevant Github READMEs updated **or** no GitHub README updates required.
- [ ] Relevant Wiki pages created/updated **or** no Wiki updates required.

### Optional
- [ ] Staging environment is unstaged before merging.
- [ ] Photo of a cute animal attached to this PR.

### CODE REVIEW

**Comment by aerlaut** [comment]
Why 'Cell sets and Metadata' and not 'Cell Sets and Metadata'?

**Comment by cosa65** [comment]
> Why 'Cell sets and Metadata' and not 'Cell Sets and Metadata'?

We have these panels
image
So it fits better.

We also have "Custom cell sets" for scratchpad and also these
image

**Comment by cosa65** [comment]
Won't "Cell sets and Metadata" right over "Cell sets" and "Metadata" feel a little redundant?

What about perhaps calling it "Cell sets management" or something like that?

**Comment by ivababukova** [comment]
> Won't "Cell sets and Metadata" right over "Cell sets" and "Metadata" feel a little redundant?
> 
> What about perhaps calling it "Cell sets management" or something like that?

Good point. But if I call them "Cell sets management", then that makes "metadata" feel out of place

**Pull request closed without merging**
