### PR TITLE
Disable multisample options

### PR DESCRIPTION
**Pull request by aerlaut**
# Background
#### Link to issue 

https://biomage.atlassian.net/browse/BIOMAGE-827

#### Link to staging deployment URL 

Multisample, with prefiltered data :
https://ui-agi-uni-multi.scp-staging.biomage.net/experiments/e52b39624588791a7889e39c617f669e/data-processing
Unisample (data integration step disabled) :
https://ui-agi-uni-multi.scp-staging.biomage.net/experiments/7d9318d157a6b17d3d6caec23a25cc86/data-processing

#### Links to any Pull Requests related to this

N.A.

#### Anything else the reviewers should know about the changes here

- Change option in gene expression to compare in sample by default
- Remove "Copy to all sample" button in data processing if there is only 1 sample
- Disable "Copy to all sample" button in data processing if "auto" is chosen.

# Changes
### Code changes

# Definition of DONE
Your changes will be ready for merging after each of the steps below have been completed:

### Testing
- [ ] Unit tests written
- [x] Tested locally with Inframock
- [X] Deployed to staging

To set up easy local testing with inframock, follow the instructions here: https://github.com/biomage-ltd/inframock
To deploy to the staging environment, follow the instructions here: https://github.com/biomage-ltd/biomage-utils

### Documentation updates
Is all relevant documentation updated to reflect the proposed changes in this PR?

- [ ] Relevant Github READMEs updated
- [ ] Relevant wiki pages created/updated

### Approvers
- [ ] Approved by a member of the core engineering team
- [ ] (UX changes) Approved by vickymorrison (this is her username, tag her if you need approval)

### Just before merging:
- [x] After the PR is approved, the `unstage` script in here: https://github.com/biomage-ltd/biomage-utils is executed. This script cleans up your deployment to staging

### Optional
- [ ] Photo of a cute animal attached to this PR

### CODE REVIEW

**Comment by ivababukova** [comment]
code-wise it makes sense, but I am not approving because I can see it marked as a draft and it doesn't look like it's been tested in staging

**Comment by cosa65** [comment]
I looked at the unisample staging link and it seems like data integration isn't disabled for me, it ismentioned in the ticket that it should.

**Review by cosa65 — COMMENTED** [review]
I looked at the unisample staging link and it seems like data integration isn't disabled for me, it ismentioned in the ticket that it should.

**Review by cosa65 — COMMENTED** [review]
Perhaps we could also add tooltips on disabled components that explain why they are not accessible (one single sample)?

**Review by cosa65 — APPROVED** [review]

**Pull request merged**
