### PR TITLE
Fix UX problems in the pipeline

### PR DESCRIPTION
**Pull request by marcellp**
# Background
#### Link to issue 
https://biomage.atlassian.net/browse/BIOMAGE-520

#### Link to staging deployment URL 
https://ui-qc-ux-changes.scp-staging.biomage.net/

#### Links to any Pull Requests related to this
N/A

#### Anything else the reviewers should know about the changes here
N/A

# Changes
### Code changes
Fixed some of the UX problems we have been having with the platform. This means the following in practice:

* the `stepsDone` and `complete` fields in the `meta` part of `processingConfig` are gone and will not be used.
* Instead, we use the pipeline settings directly to compute "steps complete", resulting in more consistent UX
* There is now an indicator for the progress of the pipeline
* Removed the alert box next to the 'Run filter' button.
* Renamed 'Run filter' and fixed the microcopy on the leaving dialog.
* Changed the 'Next' button from a primary to a secondary button so it is obvious what the main action is on the website.

# Definition of DONE
Your changes will be ready for merging after each of the steps below have been completed:

### Testing
- [x] Unit tests written
- [x] Tested locally with Inframock
- [ ] Deployed to staging

To set up easy local testing with inframock, follow the instructions here: https://github.com/biomage-ltd/inframock
To deploy to the staging environment, follow the instructions here: https://github.com/biomage-ltd/biomage-utils

### Documentation updates
Is all relevant documentation updated to reflect the proposed changes in this PR?

- [x] Relevant Github READMEs updated
- [x] Relevant wiki pages created/updated

### Approvers
- [ ] Approved by a member of the core engineering team
- [ ] (UX changes) Approved by vickymorrison (this is her username, tag her if you need approval)

### Just before merging:
- [ ] After the PR is approved, the `unstage` script in here: https://github.com/biomage-ltd/biomage-utils is executed. This script cleans up your deployment to staging

### Optional
- [x] Photo of a cute animal attached to this PR

Screenshot 2021-03-18 at 19 55 28

### CODE REVIEW

**Comment by xverges** [comment]
We have this reporting of only 5 completed steps when the pipeline has already finished, but it is unrelated to the PR: the API is reporting 5 completed steps (because, when implementing it, I assumed that the only steps that needed reporting were those inside the map)
Screenshot 2021-03-19 at 09 22 24

From the logs:
```
[2021-03-19T08:31:42.457Z] ExecutionHistory for ARN arn:aws:states:eu-west-1:242905224710:execution:biomage-pipeline-staging-01679c8daeb6af12175831e70f6264d970b89222:c422833b-274e-4c49-a6b4-7bb4d508eb1f: 60 events, 5 completed steps
```

**Comment by xverges** [comment]
I am getting an error when trying to go to the compute embedding step. I see it working on production but failing on staging

**Comment by marcellp** [comment]
> We have this reporting of only 5 completed steps when the pipeline has already finished, but it is unrelated to the PR: the API is reporting 5 completed steps (because, when implementing it, I assumed that the only steps that needed reporting were those inside the map)
> Screenshot 2021-03-19 at 09 22 24
> 
> From the logs:
> 
> ```
> [2021-03-19T08:31:42.457Z] ExecutionHistory for ARN arn:aws:states:eu-west-1:242905224710:execution:biomage-pipeline-staging-01679c8daeb6af12175831e70f6264d970b89222:c422833b-274e-4c49-a6b4-7bb4d508eb1f: 60 events, 5 completed steps
> ```

Thanks for this! We track this particular issue under https://biomage.atlassian.net/browse/BIOMAGE-669. This was not a regression introduced by this MR, but we will have to fix it. You may be able to pick it up after sprint planning if you want to.

**Comment by marcellp** [comment]
> I am getting an error when trying to go to the compute embedding step. I see it working on production but failing on staging

Should be fixed after the last commit.

**Comment by xverges** [comment]
Minor glitch in the status card: the pretty start date is not refreshed when the card is displayed
https://user-images.githubusercontent.com/460418/111761239-fa924680-889f-11eb-8dc8-d17b0200e982.mov

**Comment by xverges** [comment]
@marcellp I am unable to see the pipeline progressing in the UI. In the logs I see references only to `cellSizeDistribution`, but I see the state machine progress until it completes without error. The logs does display some errors, but they seem related to the worker.

**Review by xverges — APPROVED** [review]
lgtm, but some other component failure that I am unable to track is preventing me to see how the pipeline progresses

**Pull request merged**
