### PR TITLE
Small change to genteTable to make the geneNamesFilter compatible with r

### PR DESCRIPTION
**Pull request by ogibson**
# Background
#### Link to issue 

https://biomage.atlassian.net/browse/BIOMAGE-458?atlOrigin=eyJpIjoiZmQwZmRkZmVlNzA4NDYxOTlkMDMwNmE4ODBlNjg2MTUiLCJwIjoiaiJ9

#### Link to staging deployment URL 

https://ui-gxc51w7udznz6mygakjcu7tnpa.scp-staging.biomage.net/

#### Links to any Pull Requests related to this

https://github.com/biomage-ltd/worker/tree/listGenes-SE

#### Anything else the reviewers should know about the changes here

# Changes
### Code changes

# Definition of DONE
Your changes will be ready for merging after each of the steps below have been completed:

### Testing
- [ ] Unit tests written
- [X ] Tested locally with Inframock
- [ ] Deployed to staging

To set up easy local testing with inframock, follow the instructions here: https://github.com/biomage-ltd/inframock
To deploy to the staging environment, follow the instructions here: https://github.com/biomage-ltd/biomage-utils

### Documentation updates
Is all relevant documentation updated to reflect the proposed changes in this PR?

- [ ] Relevant Github READMEs updated
- [ ] Relevant wiki pages created/updated

### Approvers
- [ ] Approved by a member of the core engineering team
- [ ] (UX changes) Approved by vickymorrison (this is her username, tag her if you need approval)

### Just before merging:
- [ ] After the PR is approved, the `unstage` script in here: https://github.com/biomage-ltd/biomage-utils is executed. This script cleans up your deployment to staging

### Optional
- [ ] Photo of a cute animal attached to this PR
image

She's so cute.

### CODE REVIEW

**Comment by aerlaut** [comment]
The current way the search string is formatted isn't compatible with R string searches?

**Comment by ogibson** [comment]
> The current way the search string is formatted isn't compatible with R string searches?

Nope, we needed to change from % to ^ for it to work. There might be a way to do it with % in r, but this seemed quicker for me.

**Review by aerlaut — APPROVED** [review]
Changed to suit R regex. Previously, matching was done in Python.

**Comment by ivababukova** [comment]
what is the state with this? If it is approved, should we merge it?

**Comment by aerlaut** [comment]
@ogibson-biomage this will be merged together with the changes of the R worker right?

**Comment by ogibson** [comment]
> what is the state with this? If it is approved, should we merge it?

Yes, as Agi said this'll be merged as soon as the worker task is merged. I'm gonna push the security modifications Marcell suggested today, and ask Juanlu to review tomorrow so we can merge both of them together.

**Pull request merged**
