### PR TITLE
[BIOMAGE-663] Allow x-axis label rotation

### PR DESCRIPTION
**Pull request by robioson**
# Background
#### Link to issue 
https://biomage.atlassian.net/browse/BIOMAGE-663
#### Link to staging deployment URL 
https://ui-james-ui372-worker144.scp-staging.biomage.net/
#### Anything else the reviewers should know about the changes here
This PR adds a config option for all plots with axes to rotate the labels on the x-axis. This resolves the issue of labels becoming too crowded to be readable.

I tried a few alternatives in another branch:
 - Always rotating the frequency and violin plot labels when grouped by cluster
 - Rotating when the number of groups exceeded a limit
 - Rotating if the total length of the labels exceeded a limit

These had cosmetic or robustness issues. In the end, Agi and I decided to add an option for all plots.

visualization

# Changes
### Code changes
- Add a new config option in the axes group
- Apply this value in all the plot specs that have axes
# Definition of DONE
Your changes will be ready for merging after each of the steps below have been completed:

### Testing
- [x] Unit tests written
- [x] Tested locally with Inframock (with latest production data downloaded with biomage experiment pull)
- [x] Deployed to staging

To set up easy local testing with inframock, follow the instructions here: https://github.com/biomage-ltd/inframock
To deploy to the staging environment, follow the instructions here: https://github.com/biomage-ltd/biomage-utils

### Documentation updates
Is all relevant documentation updated to reflect the proposed changes in this PR?

- [ ] Relevant Github READMEs updated
- [ ] Relevant wiki pages created/updated

### Approvers
- [ ] Approved by a member of the core engineering team
- [ ] (UX changes) Approved by vickymorrison (this is her username, tag her if you need approval)

### Just before merging:
- [ ] After the PR is approved, the `unstage` script in here: https://github.com/biomage-ltd/biomage-utils is executed. This script cleans up your deployment to staging

### Optional
- [ ] Photo of a cute animal attached to this PR

### CODE REVIEW

**Comment by cosa65** [comment]
testing in staging (using K0 and WT1 from murine) when I tried to do the rotation in data integration it was not changing the labels, after going to the plots and tables frequency I am getting the following:
Screen Shot 2021-06-30 at 15 51 40

**Comment by robioson** [comment]
The frequency plot not updating is a regression introduced before this PR, trying to find it now.

**Comment by marcellp** [comment]
May be related to #362, although I fail to see how.

**Comment by robioson** [comment]
Actually it is caused by #359.

**Comment by ivababukova** [comment]
@robioson What is the status of this: is it waiting for reviews?

**Review by cosa65 — APPROVED** [review]

**Pull request merged**
