### PR TITLE
[BIOMAGE-879] - Add filter statistics table

### PR DESCRIPTION
**Pull request by aerlaut**
# Background
#### Link to issue 

https://biomage.atlassian.net/browse/BIOMAGE-879

#### Link to staging deployment URL 

https://ui-agi-ui404-api187.scp-staging.biomage.net/

#### Links to any Pull Requests related to this

UI - https://github.com/biomage-ltd/ui/pull/404
API - https://github.com/biomage-ltd/api/pull/187

#### Anything else the reviewers should know about the changes here

- Added filter statistics to the UI.

# Changes
### Code changes

# Definition of DONE
Your changes will be ready for merging after each of the steps below have been completed:

### Testing
- [x] Unit tests written
- [X] Tested locally with Inframock (with latest production data downloaded with biomage experiment pull)
- [X] Deployed to staging

To set up easy local testing with inframock, follow the instructions here: https://github.com/biomage-ltd/inframock
To deploy to the staging environment, follow the instructions here: https://github.com/biomage-ltd/biomage-utils

### Documentation updates
Is all relevant documentation updated to reflect the proposed changes in this PR?

- [ ] Relevant Github READMEs updated
- [ ] Relevant wiki pages created/updated

### Approvers
- [ ] Approved by a member of the core engineering team
- [ ] (UX changes) Approved by vickymorrison (this is her username, tag her if you need approval)

### Just before merging:
- [ ] After the PR is approved, the `unstage` script in here: https://github.com/biomage-ltd/biomage-utils is executed. This script cleans up your deployment to staging

### Optional
- [ ] Photo of a cute animal attached to this PR

### CODE REVIEW

**Comment by aerlaut** [comment]
Hi @vickymorrison, can you please take a look at this PR? This PR adds the filter statistics information for each sample

**Comment by vickymorrison** [comment]
1. The numbers shown in the '% removed' column are fractions rather than percentages - they need to be multiplied by 100 to be %.
2. Having negative values in the % removed column is quite confusing. How about showing '% change' instead of '% removed'? Then showing either a + or a - before the % value showing whether there is an increase or decrease in the statistic.
3. The table takes up quite a lot of space. The words 'filter statistics' could be moved to the top row of the table as currently this text takes up an unnecessary amount of space.
4. The words 'filter statistics' should not be bold. Also make sure that this text is the same size as the 'Filter settings' text that is in the menu. The reson for this change request is that currently my eye is drawn to 'filter statistics' because it is the most prominent text on the page whereas sample name is more important than this.
Let me know if anything doesn't make sense - happy to jump on a call.
Also worth asking @ogibson-biomage to take a look as he knows more about the actual statistcs than I do.

**Comment by aerlaut** [comment]
@ogibson-biomage can you have a look at the statistics table too?

**Comment by vickymorrison** [comment]
A very small thing: can the column width be reduced? There is a lot of white space within the table, particularly in the first column, which makes it difficult to read. I suggest keeping the column widths as standard for all samples (as is currently) rather than wrapping to the content so that all the tables are the same size (as is currently) as this looks good when scrolling through multiple samples.
This is a small point though. Otherwise it looks good to me.

**Review by vickymorrison — APPROVED** [review]

**Pull request merged**
