### PR TITLE
[BIOMAGE-1231] - Create download button menu

### PR DESCRIPTION
**Pull request by aerlaut**
# Background
#### Link to issue 

https://biomage.atlassian.net/browse/BIOMAGE-1231

#### Link to staging deployment URL 

https://ui-agi-ui412.scp-staging.biomage.net/

#### Links to any Pull Requests related to this

N.A.

#### Anything else the reviewers should know about the changes here

Button not disabled by default.

You can see the following screenshot or have a look at the staging link

image

# Changes
### Code changes

# Definition of DONE
Your changes will be ready for merging after each of the steps below have been completed:

### Testing
- [ ] Unit tests written
- [X] Tested locally with Inframock (with latest production data downloaded with biomage experiment pull)
- [X] Deployed to staging

To set up easy local testing with inframock, follow the instructions here: https://github.com/biomage-ltd/inframock
To deploy to the staging environment, follow the instructions here: https://github.com/biomage-ltd/biomage-utils

### Documentation updates
Is all relevant documentation updated to reflect the proposed changes in this PR?

- [ ] Relevant Github READMEs updated
- [ ] Relevant wiki pages created/updated

### Approvers
- [ ] Approved by a member of the core engineering team
- [ ] (UX changes) Approved by vickymorrison (this is her username, tag her if you need approval)

### Just before merging:
- [ ] After the PR is approved, the `unstage` script in here: https://github.com/biomage-ltd/biomage-utils is executed. This script cleans up your deployment to staging

### Optional
- [ ] Photo of a cute animal attached to this PR

### CODE REVIEW

**Comment by aerlaut** [comment]
Hi @vickymorrison, can you please have a look at the download button? The staging link is working

**Review by kafkasl — COMMENTED** [review]
I think it's a better option to just hide the button until there is something implemented. Otherwise, if we deploy it it will look weird having a new button (which user's tend to click when they see something new) that has no options.

**Comment by vickymorrison** [comment]
Looks good. Only 1 comment: change the tooltip text to "Coming soon!" and make sure it appears over all 3 menu options (currently it only appears over 2 of them).

I don't think it's an issue that the button is there but there are no options - we have this in other places in the platform e.g. clustering method dropdown menu where Louvain is the only option that has been implemented. Actually it may even be a positive thing as users learn what features are coming soon.

**Review by StefanBabukov — APPROVED** [review]
LGTM, can you also add tests to check if everything is rendered? *Edit* - didnt see the previous comments

**Comment by aerlaut** [comment]
> I think it's a better option to just hide the button until there is something implemented. Otherwise, if we deploy it it will look weird having a new button (which user's tend to click when they see something new) that has no options.

Ok, I'll hide the button after Vicky had a look. I think this button was created first so people can start working on the different backend implementations,

**Comment by vickymorrison** [comment]
I'll go ahead and approve with the expectation that if the button remains visible on the UI then you should update the tooltips. This is not relevant if you choose to hide the button.

**Review by vickymorrison — APPROVED** [review]

**Comment by aerlaut** [comment]
> LGTM, can you also add tests to check if everything is rendered? _Edit_ - didnt see the previous comments

Added test for `projectDetails`

**Pull request merged**
