### PR TITLE
[BIOMAGE-1237] Rename Data Management tiles

### PR DESCRIPTION
**Pull request by robioson**
# Background
#### Link to issue 
https://biomage.atlassian.net/browse/BIOMAGE-1237
#### Link to staging deployment URL 
https://ui-james-ui415.scp-staging.biomage.net/
#### Anything else the reviewers should know about the changes here
The ticket recommended changing 'Data Management' to 'Samples List', I presume to match the existing 'Projects List'. However I reasoned that for both of these, 'List' is redundant, so changed them to 'Samples' and 'Projects' respectively.
# Changes
### Code changes

# Definition of DONE
Your changes will be ready for merging after each of the steps below have been completed:

### Testing
- [ ] Unit tests written
- [ ] Tested locally with Inframock (with latest production data downloaded with biomage experiment pull)
- [ ] Deployed to staging

To set up easy local testing with inframock, follow the instructions here: https://github.com/biomage-ltd/inframock
To deploy to the staging environment, follow the instructions here: https://github.com/biomage-ltd/biomage-utils

### Documentation updates
Is all relevant documentation updated to reflect the proposed changes in this PR?

- [ ] Relevant Github READMEs updated
- [ ] Relevant wiki pages created/updated

### Approvers
- [ ] Approved by a member of the core engineering team
- [ ] (UX changes) Approved by vickymorrison (this is her username, tag her if you need approval)

### Just before merging:
- [ ] After the PR is approved, the `unstage` script in here: https://github.com/biomage-ltd/biomage-utils is executed. This script cleans up your deployment to staging

### Optional
- [ ] Photo of a cute animal attached to this PR

### CODE REVIEW

**Comment by vickymorrison** [comment]
Let me know when staging is up and I'll take a look.

**Comment by robioson** [comment]
Sorry @vickymorrison, I forgot, it's up now

**Comment by vickymorrison** [comment]
@robioson The staging link gives me a 404 error.

**Comment by robioson** [comment]
Hm, it works for me right now. Maybe I commented too soon!

**Comment by robioson** [comment]
Taking a second look, I wonder if it would perhaps be better to call the tile 'Project details' as there are other things on it than samples, like the description and ID.

**Comment by vickymorrison** [comment]
It works now! I was just too keen :-)

**Comment by vickymorrison** [comment]
You're right - 'Project details' is better

**Comment by robioson** [comment]
I've made the change @vickymorrison

**Review by vickymorrison — APPROVED** [review]

**Pull request merged**
